services:
  # 1. The API Service (Node.js)
  - type: web
    name: camcyber-api
    runtime: node
    rootDir: api-v4
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: camcyber-db
          property: connectionString

  # 2. The File Service
  - type: web
    name: camcyber-file
    runtime: node
    rootDir: file-v3
    buildCommand: npm install
    startCommand: npm start

  # 3. The Web Frontend (Angular)
  - type: web
    name: camcyber-frontend
    runtime: node
    rootDir: web-v4
    buildCommand: npm install && npm run build
    startCommand: npm start # Ensure this matches your package.json start script

# 4. The PostgreSQL Database
databases:
  - name: camcyber-db
    plan: free